services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"  
    networks:
      - app-network  

  app:
    build:
      context: .  
    ports:
      - "3000:3000"  
    depends_on:
      - db  
    networks:
      - app-network  
    environment:
      DATABASE_HOST: db 
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres

networks:
  app-network:
    driver: bridge
