services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432  
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge
